ghumfirdiary/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainapp.urls')),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'^journal/add/(?P<pk>[0-9]+)/$', views.JournalCreate.as_view(), name='journal-add'),
    url(r'^journal/update/(?P<pk>[0-9]+)/$', views.JournalUpdate.as_view(), name='journal-update'),
    url(r'^journal/delete/(?P<pk>[0-9]+)/$', views.JournalDelete.as_view(), name='journal-delete'),
]

mainapp/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    place = models.CharField(max_length=140)
    album_cover = models.FileField()

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.place


class Journal(models.Model):
    journal = models.ForeignKey(Album, on_delete=models.CASCADE)
    journal_title = models.CharField(max_length=140, blank=True)
    journal_details = models.TextField()
    date = models.CharField(max_length=100, default='')
    time = models.CharField(max_length=10, default='')
    journal_image = models.FileField(blank=True)

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.journal_title

mainapp/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
      model = User
      fields = ['username', 'email', 'password']

mainapp/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import Album, Journal
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'mainapp/add.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = "mainapp/album_detail.html"


class AlbumCreate(CreateView):
    model = Album
    fields = ['place', 'album_cover']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['place', 'album_cover']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse('index')


class JournalCreate(CreateView):
    model = Journal
    fields = ['journal', 'journal_title', 'journal_details', 'date', 'time', 'journal_image']


class JournalUpdate(UpdateView):
    model = Journal
    fields = ['journal', 'journal_title', 'journal_details', 'journal_image']


class JournalDelete(DeleteView):
    model = Journal
    success_url = reverse('index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'mainapp/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('index')

        return render(request, self.template_name, {'form': form})

mainapp/templates/mainapp/add.html
{% extends "mainapp/header.html"%}
    {% block content %}
         <div class="row">
             {% for album in object_list %}
             <div class="col-md-4">
                 <div class="col-md-12" >
                     <div class="thumbnail">
                         <a href="{% url 'detail' album.id %}">
                            <img src="{{album.album_cover.url}}" alt="Responsive image" class="img-responsive" style="width:auto; height:200px;">
                         </a>
                         <div class="caption">
                             <h3> {{album.place }}</h3>
                             <a class="btn btn-info" href="{% url 'detail' album.id %}" role="button">View Detail</a>
                             <form action="{% url 'album-delete' album.id %}" method="post" style="display:inline;" >
                                 {% csrf_token %}
                                 <input type="hidden" name="album_id" value="{{album.id }}">
                                 <button type="submit" class="btn btn-default btn-sm">
                                     <span class="glyphicon glyphicon-trash"></span>
                                 </button>
                             </form>
                             <form action="{% url 'album-update' album.id %}" method="post" style="display:inline;" >
                                 {% csrf_token %}
                                 <input type="hidden" name="album_id" value="{{album.id }}">
                                 <button type="submit" class="btn btn-default btn-sm">
                                     <span class="glyphicon glyphicon-pencil"></span>
                                 </button>
                             </form>
                         </div>
                     </div>
                 </div>
             </div>
             {% endfor %}
         </div>
    {% endblock

mainapp/templates/mainapp/album_detail.html
{% extends 'mainapp/header.html' %}
    {% block content %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 style=" text-align: center;font-family:'Droid Serif', serif; border-bottom:3px solid Black;"> {{album.place }}</h1>
                <div class="col-md-2 col-md-offset-10">
                    <a class="btn btn-info" href="{% url 'journal-add' album.id %}" role="button" style="display:inline;">Add Journal</a>
                </div>
                <div class=" col-md-12 ">
                {% for journal in album.journal_set.all %}
                    <div class="row">
                        <div class=" col-md-12">
                            <div class="panel-body" style="text-align:justify;">
                                <h3 style="font-family:'Droid Serif', serif;font-size: 40px; text-align:center; border-bottom:3px solid Black;"> {{journal.journal_title}}</h3>
                                <footer style="font-family:'Droid Serif', serif;font-size: 20px; font-weight:bold;">{{journal.date }}</footer>
                                <footer style="font-family:'Droid Serif', serif;font-size: 15px; font-weight:bold;">{{journal.time}}</footer>
                                <br>
                                <br>
                                {% if journal.journal_image.url != null %}
                                <img src="{{journal.journal_image.url}}" alt="Responsive image" class="img-responsive" style="width:auto; height:440px;">
                                {% endif%}
                                <br>
                                <p style="font-family:'Lobster', cursive; font-size: 17px;">{{journal.journal_details}}</p>
                                <form action="{% url 'journal-update' journal.id %}" method="post" style="display:inline;" >
                                {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{album.id }}">
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </form>
                                <form action="{% url 'journal-delete' journal.id %}" method="post" style="display:inline;" >
                                {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{album.id }}">
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    {%endblock %}

mainapp/templates/mainapp/album_form.html
{% extends 'mainapp/header.html' %}
    {% block content %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-7 col-md-offset-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'mainapp/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-sm-sm-6">
                                        <button type="submit" class="btn btn-success" value="Save">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

mainapp/templates/mainapp/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-6 col-sm-sm-6">
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div clsss="col-sm-10"> {{ field }}</div>
    </div>
{% endfor %}

mainapp/templates/mainapp/header.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
        <link href="{% static 'css/mycss.css'%}" rel="stylesheet">
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Arvo|Farsan|Lobster|Tangerine|Alice" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif|Varela+Round" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif|Varela+Round|Lobster" rel="stylesheet">
    </head>

    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="{% url 'index' %}" class="navbar-brand">GHUMFHIR-DIARY</a>
                </div>
                <div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}" style="margin-right: 5px;">Home</a></li>
                    </ul>
                </div>
                <div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}" style="margin-right: 5px;">Contacts</a></li>
                    </ul>
                </div>
                <div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}">Help</a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'album-add'%}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;LogOut
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'album-add'%}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right" style="margin-top:8px;">
                    <input type="text" class="form-control" placeholder="Search">
                </ul>
            </div>
        </nav>
	    {% block content%}
	    {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

mainapp/templates/mainapp/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Jim+Nightshade" rel="stylesheet">
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <title>Page title</title>
        <style>
            body{
                background-image:url(home.jpg);
                background-position: top-left;
                background-repeat: no-repeat;
                background-size: cover;

            }
            .wrapper {
                text-align: center;
                margin-top:100px;
            }

            .btn btn-success {
                margin-right: 20px;
                position: absolute;
                top: 50%;
            }

            .btn btn-info {
                position:center-vertical;
                top: 50%;
                bottom:50%;
                left:50%;
                right:50%;

            }
        </style>
    </head>

    <body>
        <div class="wrapper">
            <h1 style="font-family: 'Jim Nightshade', cursive;font-size: 50px; text-align:center;">Ghum-Fir Diary</h1>
            <a href="http://127.0.0.1:8000/mainapp/register/"><button type="button" class="btn btn-success" style=" margin-right:20px;font-family:'Droid Serif', serif;font-size: 25px; text-align:center">Sign up</button></a>
            <a href="http://127.0.0.1:8000/login/"><button type="button" class="btn btn-info" style="font-family:'Droid Serif', serif;font-size: 25px; text-align:center">Login</button></a>
        </div>
    </body>
</html>

mainapp/templates/mainapp/journal_form.html
{% extends 'mainapp/header.html' %}
    {% block content %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-7 col-md-offset-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'mainapp/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-sm-sm-6">
                                        <button type="submit" class="btn btn-success" value="Save">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

mainapp/templates/mainapp/login.html
{% extends 'mainapp/header.html' %}
    {% block content %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-9 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div id="content-container" class="container p-none">
                                <div class="lgn-container col-lg-8">
                                    <form id="login-form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
                                    {% csrf_token %}
                                        <table class="table">
                                            <tr>
                                                <td><label for="id_username">Username</label></td>
                                                <td><input id="id_username" name="username" type="text" class="form-control"></td>
                                            </tr>
                                            <tr>
                                                <td><label for="id_password">Password</label></td>
                                                <td><input id="id_password" name="password" type="password" class="form-control"></td>
                                            </tr>
                                        </table>
                                        {% if form.errors %}
                                        <p class=" label label-danger">
                                            Your username and password didn't match.
                                            Please try again.
                                        </p>
                                        {% endif %}
                                        <div class="row" >
                                            <div class="col-md-1 col-md-offset-6">
                                                <input type="submit" value="Login" class="btn btn-primary pull-centre" />
                                                <input type="hidden" name="next" value="{{ next }}" />
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}

mainapp/templates/mainapp/registration_form.html
{% extends 'mainapp/header.html' %}
    {% block content %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-7 col-md-offset-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'mainapp/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-sm-sm-6">
                                        <button type="submit" class="btn btn-success" value="Save">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}